Add payment method: MBWAY
buckaroo-it/PrestaShop pull request #68
Opened 2023-10-19 12:23 UTC by Rinor12010

2023-10-19 14:03 UTC, vegimcarkaxhija approved these changes

2023-10-19 14:03 UTC, vegimcarkaxhija commented on src/Repository/RawPaymentMethodRepository.php
> +            ['name' => 'mbway', 'label' => 'MB WAY', 'icon' => 'mbway.png', 'template' => '', 'is_payment_method' => '1'],
image is missing also it needs to be SVG

2023-10-20 08:15 UTC, harli91 commented on api/paymentmethods/mbway/mbway.php
> +}
you don't need this method

2023-10-20 08:27 UTC, vegimcarkaxhija requested changes

2023-10-20 08:27 UTC, vegimcarkaxhija commented on src/Repository/RawPaymentMethodRepository.php
> +            ['name' => 'mbway', 'label' => 'MB WAY', 'icon' => 'mbway.png', 'template' => '', 'is_payment_method' => '1'],
image is missing also it needs to be SVG

2023-10-20 11:22 UTC, vegimcarkaxhija approved these changes

2023-10-20 11:22 UTC, merged