Bp 3091 add financial warning for the use of bnpl methods presta shop
buckaroo-it/PrestaShop pull request #89
Opened 2023-11-07 13:40 UTC by Rinor12010

2023-11-07 13:52 UTC, vegimcarkaxhija requested changes

2023-11-07 13:52 UTC, vegimcarkaxhija commented on src/Repository/RawPaymentMethodRepository.php
> +                $configValue['financial_warning'] = 1;
save financial_warning as boolean, so below you check if its true or false and not === 1

2023-11-07 14:40 UTC, harli91 commented on dev/src/components/payments/AfterpayPaymentConfig.vue
> +    methods: {
why don't you set the `financial_warning` value in the `FinancialWarning` component?

2023-11-08 11:09 UTC, vegimcarkaxhija approved these changes

2023-11-08 11:15 UTC, merged